obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.5, -0.5], [0.5, 0.5], [-0.5, 0.5], [-0.5, -0.5]]
#robot_radius: ir_of_robot
inflation_radius: 0.55

observation_sources: point_cloud_sensor

point_cloud_sensor: {sensor_frame: wamv/lidar_wamv_link, data_type: PointCloud2, topic: /wamv/sensors/lidars/lidar_wamv/points, marking: true, clearing: true}